---
- name: Consul | HAProxy Server provisioning
  hosts: localhost
  become: true

  tasks:

   - name: Consul | HAProxy | Git Clone
     git:
       repo: 'https://github.com/hashicorp/terraform-aws-consul.git'
       dest: /home/ubuntu/terraform-aws-consul

   - name: Consul | HAProxy |  Shell command Installing Consul
     shell: "terraform-aws-consul/modules/install-consul/install-consul --version 0.9.1"
     become: yes
     become_method: sudo

   - name: Consul | HAProxy |  Shell command run-consul
     shell: "/opt/consul/bin/run-consul --client --cluster-tag-key consul-cluster --cluster-tag-value consul-group --datacenter $(cat /home/ubuntu/datacenter)"
     become: yes
     become_method: sudo

   - name: Consul Servers | correcting config
     replace:
       path: /opt/consul/config/default.json
       after: 'migration\": false'
       before: '}'
       regexp: '^(.+)$'
       replace: ''

   - name: Consul Servers | correcting config
     replace:
       path: /opt/consul/config/default.json
       regexp: '"ui"'
       replace: '"enable_script_checks": true, "ui"'

   - name: Consul | HAProxy | Copy HAProxy json files to /opt/consul/config
     copy:
       src: /home/ubuntu/haproxy.service.json
       dest: /opt/consul/config/

   - name: Consul | HAProxy | Restart consul
     systemd:
       name: consul
       enabled: yes
       state: restarted
     become: true
     become_method: sudo

   - name: HAProxy | Install haproxy package
     apt:
       name: haproxy
       state: present
     become: true
     become_method: sudo

   - name: HAProxy | Copy haproxy config file
     copy:
       src: /home/ubuntu/haproxy.cfg
       dest: /etc/haproxy/haproxy.cfg
     become: true
     become_method: sudo

   - name: HAProxy | Enable haproxy at boot
     systemd:
       name: haproxy
       enabled: yes
       state: restarted
     become: true
     become_method: sudo