---
- name: Consul | HAProxy Server provisioning
  hosts: localhost
  become: true

  tasks:

   - name: Consul | HAProxy | Git Clone
     git:
       repo: 'https://github.com/hashicorp/terraform-aws-consul.git'
       dest: /home/ubuntu/terraform-aws-consul

   - name: Consul | HAProxy |  Shell command Installing Consul
     shell: "terraform-aws-consul/modules/install-consul/install-consul --version 1.5.1"
     become: yes
     become_method: sudo

   - name: Consul | HAProxy |  Shell command run-consul
     shell: "/opt/consul/bin/run-consul --client --skip-consul-config"
     become: yes
     become_method: sudo

   - name: Consul | HAProxy | Wait until the file haproxy.client.json is present before continuing
     wait_for:
       path: /home/ubuntu/haproxy.client.json

   - name: Consul | HAProxy | Get local IP
     shell: cat /home/ubuntu/local_ip
     register: ipv4_addr
  
   - name: Consul | HAProxy | Set local address in Config file
     replace:
       path: /home/ubuntu/haproxy.client.json
       regexp: server_ip
       replace: "{{ipv4_addr.stdout}}"

   - name: Consul | HAProxy | Copy HAProxy config files to /opt/consul/config
     copy:
       src: /home/ubuntu/haproxy.client.json
       dest: /opt/consul/config/default.json

   - name: Consul | HAProxy | Copy HAProxy service files to /opt/consul/config
     copy:
       src: /home/ubuntu/haproxy.service.json
       dest: /opt/consul/config/

   - name: Consul | HAProxy | Restart consul
     systemd:
       name: consul
       enabled: yes
       state: restarted
     become: true
     become_method: sudo

   - name: HAProxy | Install haproxy package
     apt:
       name: haproxy
       state: present
     become: true
     become_method: sudo

   - name: HAProxy | Copy haproxy config file
     copy:
       src: /home/ubuntu/haproxy.cfg
       dest: /etc/haproxy/haproxy.cfg
     become: true
     become_method: sudo

   - name: HAProxy | Enable haproxy at boot
     systemd:
       name: haproxy
       enabled: yes
       state: restarted
     become: true
     become_method: sudo