---
- name: Consul | Server provisioning
  hosts: localhost
  become: true

  tasks:

   - name: Consul | Server | Git Clone
     git:
       repo: 'https://github.com/hashicorp/terraform-aws-consul.git'
       dest: /home/ubuntu/terraform-aws-consul

   - name: Consul | Server |  Shell command Installing Consul
     shell: "terraform-aws-consul/modules/install-consul/install-consul --version 0.9.1"
     become: yes
     become_method: sudo

   - name: Consul | Server |  Shell command run-consul
     shell: "/opt/consul/bin/run-consul --server --cluster-tag-key consul-cluster --cluster-tag-value consul-group --datacenter $(cat /home/ubuntu/az)"
     become: yes
     become_method: sudo

   - name: Consul Servers | correcting config
     replace:
       path: /opt/consul/config/default.json
       after: 'migration\": false'
       before: '}'
       regexp: '^(.+)$'
       replace: ''

   - name: Consul Servers | correcting config
     replace:
       path: /opt/consul/config/default.json
       regexp: '"ui"'
       replace: '"enable_script_checks": true, "ui"'

   - name: Consul | Server | Copy Server json files to /opt/consul/config
     copy:
       src: /home/ubuntu/consul.server.json
       dest: /opt/consul/config/

   - name: Consul | Server | Restart consul
     systemd:
       name: consul
       enabled: yes
       state: restarted
     become: true
     become_method: sudo
