---
- name: Install K8S minion services
  hosts: localhost
  tasks:

    - name: K8S | Install Minion | Wait until k8s-common.yaml ends before continuing
      wait_for:
        path: /home/ubuntu/k8s-common.finish

    - name: K8S | Install Minion | Wait until install-docker.yaml ends before continuing
      wait_for:
        path: /home/ubuntu/docker.finish

    - name: K8S | Install Minion | Wait until the file vars.yaml is present before continuing
      wait_for:
        path: /home/ubuntu/vars.yaml

    - name: General | Load varibles
      include_vars:
        file: vars.yaml

    - name: K8S | Install Minion | Wait for etcd on Master
      wait_for:
        host: "{{ k8s_master_ip }}"
        port: 2380
        state: started

    - name: K8S | Install Minion |  Set node tag in Config file
      replace:
        path: /home/ubuntu/config.yaml
        regexp: NODE_TYPE
        replace: "{{ node_tag }}"

    - name: Consul | HAProxy | Set master address in Config file
      replace:
        path: /home/ubuntu/config.yaml
        regexp: MASTER_IP
        replace: "{{ k8s_master_ip }}"

    - name: Consul | HAProxy | Set local address in Config file
      replace:
        path: /home/ubuntu/config.yaml
        regexp: TOKEN
        replace: "{{ kubeadm_token }}"
        
    - name: K8S | Install Minion | Join K8S with kubeadm
      shell: kubeadm join --config /home/ubuntu/config.yaml 
      become: true
      become_method: sudo
